<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%
	String path = request.getContextPath();
	if (request.getParameter("language") != null
			&& request.getParameter("language").equals("zh_CN")) {
		response.sendRedirect(path + "/page/inte/inte1.jsp?language=zh_CN");
	}
%>
<!DOCTYPE HTML>
<html>
	<head>
		<jsp:include page="/common/head.jsp" />
	</head>

<body>
	<jsp:include page="/common/top.jsp"></jsp:include>
	<div id="container">
		<jsp:include page="/common/left.jsp">
			<jsp:param value="inte_1" name="pageType" />
		</jsp:include>
		<!-- treeView end -->
		<div class="content">
			<h1>Application Integration Application</h1>
			<div class="text-section">
				<p class="section">The application integrated by ConnSec
					authentication center must apply for registration first, which can
					be OAuth application registration and SAML application
					registration.</p>
			</div>
			<!-- 一段描述结束 -->
			<h3>OAuth application integration registration requires the
				following information:</h3>
			<table class="basisTable" cellspacing="1">
				<thead>
					<th>No.</th>
					<th>OAuth Application Registration Information</th>
					<th>Description</th>
				</thead>
				<tbody>
					<tr>
						<td>1</td>
						<td>Application ID</td>
						<td>appId/client_id</td>
					</tr>
					<tr>
						<td>2</td>
						<td>Application secret</td>
						<td>appSecret /client_secret automatically generated by
							system, can be generated again</td>
					</tr>
					<tr>
						<td>3</td>
						<td>Application access url</td>
						<td>url that application accesses directly</td>
					</tr>
					<tr>
						<td>4</td>
						<td>Application OAuth token url</td>
						<td>Authentication redirect url as authentication completed,
							parameter is code</td>
					</tr>

					<tr>
						<td>5</td>
						<td>Application description</td>
						<td>Information describing the application functions</td>
					</tr>
					<tr>
						<td>6</td>
						<td>Approach to support authentication</td>
						<td>Authorization_Code/password, multi-choice</td>
					</tr>
					<tr>
						<td>7</td>
						<td>Applicant</td>
						<td>Name of applicant</td>
					</tr>
					<tr>
						<td>8</td>
						<td>Email of Applicant</td>
						<td>Email of Applicant</td>
					</tr>
				</tbody>
			</table>

		</div>
		<!-- content end -->
		<!-- //content end -->
		<div class="clear"></div>
	</div>
	<div id="footer">
		<jsp:include page="/common/footer.jsp"/>
	</div>
</body>
</html>
